[package]
name = "crypto-learn"
version = "0.1.0"
authors = ["Aleksey Bilogur <aleksey@residentmar.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.2"
hmac = "0.10.1"
ecdsa = "0.9.0"
p256 = "0.6.0"